name: Daily Heartopia Tracker

on:
  # schedule:
    # 已改用cron-job.org
    # UTC 時間 07:00 等於香港/台灣時間早上 14:00
    # - cron: '0 6 * * *'
  workflow_dispatch: # 允許在 GitHub 頁面上手動觸發測試

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py
